services:
  postgres:
    image: postgres:17
    container_name: duende_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass#4o&6
      POSTGRES_DB: DuendeIS
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
